# Generated by Django 5.2.3 on 2025-07-03 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_role_options_role_created_at_role_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={},
        ),
    ]
