# Generated by Django 5.2.3 on 2025-07-03 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_menu', models.CharField(max_length=100)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('tersedia', 'Tersedia'), ('habis', 'Habis'), ('belum', 'Belum Tersedia')], default='tersedia', max_length=10)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.kategorimenu')),
            ],
        ),
        migrations.CreateModel(
            name='GambarMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to='menu/')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gambar_menu', to='menus.menu')),
            ],
        ),
    ]
