# Generated by Django 5.2.3 on 2025-07-03 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_alter_menu_kategori'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategorimenu',
            options={'verbose_name_plural': 'Kategori Menu'},
        ),
    ]
